#!/usr/bin/env bash
# A bash script that will display information about subdomains.

# Function to display information about a subdomain
display_subdomain_info() {
    local domain=$1
    local subdomain=$2
    local record_type=$(dig +short -t A "$subdomain.$domain" | awk '{print "A"}')
    local destination=$(dig +short "$subdomain.$domain")

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Main function to display information for subdomains
audit_domain() {
    local domain=$1

    # Display information for default subdomains
    display_subdomain_info "$domain" "www"
    display_subdomain_info "$domain" "lb-01"
    display_subdomain_info "$domain" "web-01"
    display_subdomain_info "$domain" "web-02"
}

# Check if both arguments are provided
if [[ $# -eq 2 ]]; then
    audit_domain "$1" "$2"
elif [[ $# -eq 1 ]]; then
    # Display information for default subdomains
    audit_domain "$1"
else
    echo "Usage: $0 <domain> [<subdomain>]"
    exit 1
fi
