#!/usr/bin/env bash
# A bash script configure your Nginx server so that /redirect_me is redirecting to another page
# Install Nginx if not already installed
if !command -v nginx &> /dev/null; then
	sudo apt update
	sudo apt install nginx -y
fi
# Create a configuration file for the redirection
echo "
server {
    listen 80;
    server_name your_domain.com;

    location /redirect_me {
        return 301 https://www.example.com/redirected_page;
    }
}
" | sudo tee /etc/nginx/sites-available/redirect.conf

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/

# Test Nginx configuration for syntax errors
sudo nginx -t

# If the test is successful, reload Nginx to apply the changes
sudo systemctl reload nginx
