#!/usr/bin/env bash
# A bash script to configure a second web server and Nginx so that its HTTP response.
# Update package index and install Nginx
sudo apt update
sudo apt install nginx -y

# Define the custom header configuration
CUSTOM_HEADER_CONFIG="add_header X-Served-By \$hostname;"

# Add the custom header configuration to the default Nginx configuration file
echo "$CUSTOM_HEADER_CONFIG" | sudo tee -a /etc/nginx/nginx.conf > /dev/null

# Test Nginx configuration for syntax errors
sudo nginx -t

# If the test is successful, reload Nginx to apply the changes
sudo systemctl reload nginx
