#!/usr/bin/env bash
# A bash script to configure a second web server and Nginx so that its HTTP response.
# Update package index and install Nginx
sudo apt update
sudo apt install nginx -y

# Get the hostname of the server
HOSTNAME=$(hostname)

# Create a configuration file for the custom header
echo "
server {
    listen 80;
    server_name localhost;

    location / {
        # Add custom HTTP header
        add_header X-Served-By $HOSTNAME;
    }
}
" | sudo tee /etc/nginx/sites-available/custom_header

# Create a symbolic link to enable the new configuration
sudo ln -s /etc/nginx/sites-available/custom_header /etc/nginx/sites-enabled/

# Test Nginx configuration for syntax errors
sudo nginx -t

# If the test is successful, reload Nginx to apply the changes
sudo systemctl reload nginx
