#!/usr/bin/env bash
# A bash script that install and configure HAproxy on your lb-01 server.
# Install HAProxy
apt update
apt install haproxy -y

# Configure HAProxy
cat <<EOF > /etc/haproxy/haproxy.cfg
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    server web1 526787-web-01:80 check
    server web2 526787-web-02:80 check
EOF

# Restart HAProxy to apply changes
systemctl restart haproxy
