#!/usr/bin/env bash
# A bash script that checks if all server’s active IPv4 IPs on nginx listen to port 80

# Get a list of active IPv4 IPs on the server
active_ips=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d'/' -f1)

# Check if Nginx is listening on port 80 for each active IP
for ip in $active_ips; do
    if sudo netstat -tuln | grep -q ":80 " | grep -q "$ip"; then
        echo "Nginx is listening on port 80 for IP: $ip"
    fi
done
