#!/usr/bin/env bash
# A script that displays bad luck on 4th iteration and good luck on 8th itera#+ tion
dan='Best School'
i=1
while [ $i -le 10 ]
do
if [ $i -eq 4 ];then
echo "bad luck"
elif [ $i -eq 8 ];then
echo "good luck"
else
echo "$dan"
fi
((i++))
done
