#!/usr/bin/env bash
# A script that installs ufw

# Update package list
sudo apt update

# Install UFW
sudo apt install ufw

# Set default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

# Allow specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

# Enable UFW
sudo ufw enable

# Check status
sudo ufw status
