#!/usr/bin/env bash

# Define variables for server IP/domain and port (if non-default)
server="52.91.168.104"
port="22"
private_key="/root/.ssh/school"

# SSH connection command using single-character flags
ssh -i "$private_key" -p "$port" "ubuntu@$server"
