#!/usr/bin/env bash
# A bash script that creates an RSA key pair.

# Define variables
key_name="school"
key_bits="4096"
passphrase="betty"
# Generate RSA key pair with passphrase
openssl genpkey -algorithm RSA -out ~/.ssh/"$key_name" -aes256 -pass pass:"$passphrase" -pkeyopt rsa_keygen_bits:"$key_bits"

echo "RSA key pair generated successfully:"
echo "Private key: ~/.ssh/$key_name"
echo "Public key: ~/.ssh/$key_name.pub"
